name: train-model
'on':
  push:
    branches:
      - main
jobs:
  train:
    runs-on: ubuntu-latest

    defaults: 
      run:
          working-directory: capstone_worflow

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare .env
        run: |
          cp .env.example .env || true
          echo "MLFLOW_TRACKING_URI=file:./mlruns" >> .env
          echo "DATA_PATH=data/salary.csv" >> .env
          echo "ARTIFACTS_DIR=artifacts" >> .env

      - name: Run EDA
        run: python -m eda

      - name: Run Training
        run: python -m train